[project]
name = "unable-retrieve-contract"
authors = []
description = ""
telemetry = false
boot_contracts = ["pox", "costs-v2", "bns"]

[[project.requirements]]
contract_id = "SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-swap-v2-1"

[project.cache_location]
path = ".requirements"
[contracts.counter]
path = "contracts/counter.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
